[book]
language = "en"
multilingual = false
src = "src"
title = "UE4SS Documentation"

[output.html]
additional-css = ["css/custom.css"]

[output.html.fold]
enable = true
level = 1

[preprocessor.alerts]