# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

# Global Settings
FLAVOR_SUGGESTIONS: false
APPLY_FIXES: false
PRINT_ALL_FILES: false
SHOW_ELAPSED_TIME: true

# Linter List
ENABLE_LINTERS:
  - "JSON_JSONLINT"
  - "ACTION_ACTIONLINT"

