[package]
name = "patternsleuth_bind"
version = "0.1.0"
edition = "2021"

[dependencies]
patternsleuth = { path = "../patternsleuth/patternsleuth", features = ["process-internal"] }

[lib]
crate-type=["staticlib", "cdylib"]
