[FUObjectItem]
; Total Size: 0x18
; UObjectBase*                        Size: 0x0008
Object = 0x0
; int32                               Size: 0x0004
Flags = 0x8
; int32                               Size: 0x0004
ClusterRootIndex = 0xC
; int32                               Size: 0x0004
SerialNumber = 0x10
 ; modified from 0x18 to 0x14
UEP_TotalSize = 0x14