[UField]
; Total Size: 0x30
; UField*                             Size: 0x0008
Next = 0x30
UEP_TotalSize = 0x30

[UStruct]
; Total Size: 0xB0
; UStruct*                            Size: 0x0008
SuperStruct = 0x48
; UField*                             Size: 0x0008
Children = 0x50
; FField*                             Size: 0x0008
ChildProperties = 0x58
; int32                               Size: 0x0004
PropertiesSize = 0x60
; int32                               Size: 0x0004
MinAlignment = 0x64
; TArray<unsigned char,TSizedDefaultAllocator<32> > Size: 0x0010
Script = 0x68
; FProperty*                          Size: 0x0008
PropertyLink = 0x78
; FProperty*                          Size: 0x0008
RefLink = 0x80
; FProperty*                          Size: 0x0008
DestructorLink = 0x88
; FProperty*                          Size: 0x0008
PostConstructLink = 0x90
; TArray<UObject *,TSizedDefaultAllocator<32> > Size: 0x0010
ScriptAndPropertyObjectReferences = 0x98
; TArray<TTuple<TFieldPath<FField>,int>,TSizedDefaultAllocator<32> >* Size: 0x0008
UnresolvedScriptProperties = 0xA8
UEP_TotalSize = 0xB8

[UClass]
; Total Size: 0x230
; std::function<void(const void*)>*   Size: 0x0008
ClassConstructor = 0xB8
; std::function<UObject*(void*)>*     Size: 0x0008
ClassVTableHelperCtorCaller = 0xC0
; std::function<void(UObject*, void*)>* Size: 0x0008
ClassAddReferencedObjects = 0xC8
; uint32                              Size: 0x0004
ClassUnique = 0xD0:0:31:4
; uint32                              Size: 0x0004
bCooked = 0xD0:31:1:4
; EClassFlags                         Size: 0x0004
ClassFlags = 0xD4
; EClassCastFlags                     Size: 0x0008
ClassCastFlags = 0xD8
; UClass*                             Size: 0x0008
ClassWithin = 0xE0
; UObject*                            Size: 0x0008
ClassGeneratedBy = 0xE8
; FName                               Size: 0x0008  Padding: 0x10
ClassConfigName = 0xF0
; TArray<UField *,TSizedDefaultAllocator<32> > Size: 0x0010
NetFields = 0x108
; int32                               Size: 0x0004  Padding: 0x4
FirstOwnedClassRep = 0x118
; UObject*                            Size: 0x0008
ClassDefaultObject = 0x120
; void*                               Size: 0x0008
SparseClassData = 0x128
; UScriptStruct*                      Size: 0x0008
SparseClassDataStruct = 0x130
; TMap<FName, UFunction *>            Size: 0x0050
FuncMap = 0x138
; TMap<FName, UFunction *>            Size: 0x0050  Padding: 0x8
SuperFuncMap = 0x188
; TArray<FImplementedInterface,TSizedDefaultAllocator<32> > Size: 0x0010
Interfaces = 0x1E0
; FGCReferenceTokenStream             Size: 0x0010  Padding: 0x28
ReferenceTokenStream = 0x1F0
; TArray<FNativeFunctionLookup,TSizedDefaultAllocator<32> > Size: 0x0010
NativeFunctionLookupTable = 0x228
UEP_TotalSize = 0x230

[UScriptStruct]
; Total Size: 0xC0
; EStructFlags                        Size: 0x0004
StructFlags = 0xB8
; bool                                Size: 0x0001  Padding: 0x3
bPrepareCppStructOpsCompleted = 0xBC
; UScriptStruct::ICppStructOps*       Size: 0x0008
CppStructOps = 0xC0
UEP_TotalSize = 0xC0

[UFunction]
; Total Size: 0xE0
; EFunctionFlags                      Size: 0x0004
FunctionFlags = 0xB8
; uint8                               Size: 0x0001  Padding: 0x1
NumParms = 0xBC
; uint16                              Size: 0x0002
ParmsSize = 0xBE
; uint16                              Size: 0x0002
ReturnValueOffset = 0xC0
; uint16                              Size: 0x0002
RPCId = 0xC2
; uint16                              Size: 0x0002  Padding: 0x2
RPCResponseId = 0xC4
; FProperty*                          Size: 0x0008
FirstPropertyToInit = 0xC8
; UFunction*                          Size: 0x0008
EventGraphFunction = 0xD0
; int32                               Size: 0x0004  Padding: 0x4
EventGraphCallOffset = 0xD8
; std::function<void(UObject*, FFrame&, void* const)>* Size: 0x0008
Func = 0xE0
UEP_TotalSize = 0xE0

[UEnum]
; Total Size: 0x60
; FString                             Size: 0x0010
CppType = 0x38
; TArray<TTuple<FName,__int64>,TSizedDefaultAllocator<32> > Size: 0x0010
Names = 0x48
; UEnum::ECppForm                     Size: 0x0004  Padding: 0x4
CppForm = 0x58
; std::function<FText(int32)>*        Size: 0x0008
EnumDisplayNameFn = 0x60
UEP_TotalSize = 0x60