[FProperty]
; Entirety of FField is unchanged, but FProperty has some changes.
; int32                               Size: 0x0004
; UNCHANGED
ArrayDim = 0x30
; int32                               Size: 0x0004
; UNCHANGED
ElementSize = 0x34
; EPropertyFlags                      Size: 0x0008
; UNCHANGED
PropertyFlags = 0x38
; uint16                              Size: 0x0002  Padding: 0x2
; UNKNOWN IF UNCHANGED
; I SUSPECT 4 BYTES WERE ADDED AFTER RepIndex, BUT I CAN'T VERIFY THIS.
RepIndex = 0x40
; int32                               Size: 0x0004
Offset_Internal = 0x48
; FProperty*                          Size: 0x0008
; Originally: 0x48
PropertyLinkNext = 0x50
; FProperty*                          Size: 0x0008
; Originally: 0x50
NextRef = 0x58
; FProperty*                          Size: 0x0008
; Originally: 0x58
DestructorLinkNext = 0x60
; FProperty*                          Size: 0x0008
; Originally: 0x60
PostConstructLinkNext = 0x68
; FName                               Size: 0x0008
; Originally: 0x68
RepNotifyFunc = 0x70
; Originally: 0x70
UEP_TotalSize = 0x74

[FMulticastDelegateProperty]
; Total Size: 0x78
; TObjectPtr<UFunction>               Size: 0x0008
SignatureFunction = 0x78
UEP_TotalSize = 0x80

[FObjectPropertyBase]
; Total Size: 0x78
; TObjectPtr<UClass>                  Size: 0x0008
PropertyClass = 0x78
UEP_TotalSize = 0x80

[FStructProperty]
; Total Size: 0x78
; TObjectPtr<UScriptStruct>           Size: 0x0008
Struct = 0x78
UEP_TotalSize = 0x80

[FArrayProperty]
; Total Size: 0x78
; EArrayPropertyFlags                 Size: 0x0001  Padding: 0x7
; Originally: 0x70
ArrayFlags = 0x78
; FProperty*                          Size: 0x0008
Inner = 0x80
UEP_TotalSize = 0x88

[FMapProperty]
; Total Size: 0xA0
; FProperty*                          Size: 0x0008
KeyProp = 0x78
; FProperty*                          Size: 0x0008
ValueProp = 0x80
; FScriptMapLayout                    Size: 0x0018
MapLayout = 0x88
; EMapPropertyFlags                   Size: 0x0001
MapFlags = 0xA0
UEP_TotalSize = 0xA8

; This might be offset by another 4 bytes, meaning FieldSize starts at 0x78 instead of 0x70
[FBoolProperty]
; Total Size: 0x78
; uint8                               Size: 0x0001
FieldSize = 0x74
; uint8                               Size: 0x0001
ByteOffset = 0x75
; uint8                               Size: 0x0001
ByteMask = 0x76
; uint8                               Size: 0x0001
FieldMask = 0x77
UEP_TotalSize = 0x7C

[FByteProperty]
; Total Size: 0x78
; TObjectPtr<UEnum>                   Size: 0x0008
Enum = 0x78
UEP_TotalSize = 0x80

[FEnumProperty]
; Total Size: 0x80
; FNumericProperty*                   Size: 0x0008
UnderlyingProp = 0x78
; TObjectPtr<UEnum>                   Size: 0x0008
Enum = 0x80
UEP_TotalSize = 0x88

[FClassProperty]
; Total Size: 0x80
; TObjectPtr<UClass>                  Size: 0x0008
MetaClass = 0x80
UEP_TotalSize = 0x88

[FSoftClassProperty]
; Total Size: 0x80
; TObjectPtr<UClass>                  Size: 0x0008
MetaClass = 0x80
UEP_TotalSize = 0x88

[FDelegateProperty]
; Total Size: 0x78
; TObjectPtr<UFunction>               Size: 0x0008
SignatureFunction = 0x78
UEP_TotalSize = 0x80

[FInterfaceProperty]
; Total Size: 0x78
; TObjectPtr<UClass>                  Size: 0x0008
InterfaceClass = 0x78
UEP_TotalSize = 0x80

[FFieldPathProperty]
; Total Size: 0x78
; FFieldClass*                        Size: 0x0008
PropertyClass = 0x78
UEP_TotalSize = 0x80

[FSetProperty]
; Total Size: 0x90
; FProperty*                          Size: 0x0008
ElementProp = 0x78
; FScriptSparseSetLayout              Size: 0x0014
SetLayout = 0x80
UEP_TotalSize = 0x98
